/* eslint-disable @typescript-eslint/camelcase */
module.exports = {
    endPoint: 'wss://dotws.cybex.io/',
    types: {
        TradePair: {
            hash: 'H256',
            base: 'H256',
            quote: 'H256',
            latest_matched_price: 'Option<u128>',
            one_day_trade_volume: 'Balance',
            one_day_highest_price: 'Option<u128>',
            one_day_lowest_price: 'Option<u128>',
        },
        Token: {
            hash: 'H256',
            symbol: 'Vec<u8>',
            total_supply: 'Balance',
        },
        OrderLinkedItem: {
            prev: 'Option<u64>',
            next: 'Option<u64>',
            price: 'Option<u64>',
            buy_amount: 'u128',
            sell_amount: 'u128',
            orders: 'Vec<Balance>',
        },
        Price: 'u128',
        OrderType: 'u8',
        OrderStatus: 'u8',
        LimitOrder: {
            hash: 'H256',
            base: 'H256',
            quote: 'H256',
            owner: 'AccountId',
            price: 'Price',
            sell_amount: 'Balance',
            buy_amount: 'Balance',
            remained_sell_amount: 'Balance',
            remained_buy_amount: 'Balance',
            otype: 'OrderType',
            status: 'OrderStatus',
        },
        Trade: {
            hash: 'H256',
            base: 'H256',
            quote: 'H256',
            buyer: 'AccountId',
            seller: 'AccountId',
            maker: 'AccountId',
            taker: 'AccountId',
            otype: 'OrderType',
            price: 'Price',
            base_amount: 'Balance',
            quote_amount: 'Balance',
        },
    },
};
